services:
  - type: web
    name: solana-wallet-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: your_new_bot_token_here
      - key: HELIUS_API_KEY
        value: your_helius_api_key_here
      - key: WEBHOOK_URL
        value: https://your-app.onrender.com
