services:
  - type: web
    name: tg-roastbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /ping
    autoDeploy: true
    envVars:
      - key: TG_TOKEN
        value: your-telegram-bot-token
      - key: GROQ_API_KEY
        value: your-groq-key
      - key: GROQ_MODEL
        value: mixtral-8x7b
